# Generated by Django 4.2.18 on 2025-01-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
